// Build-time helper that compiles the React app (`src/app/main.tsx`)
// into a single self-contained IIFE bundle, then splices that bundle and
// the stylesheet (`src/app/styles.css`) into the outer HTML shell
// declared in `src/baseTemplate.ts`. The result is emitted to
// `src/gen/template.ts` as the `EVM_ESCROW_PAYWALL_TEMPLATE` string
// constant that `src/paywall.ts` imports at runtime.
//
// Invoked from `package.json` via `tsx src/build.ts` (the `build:app`
// script). Must run before `tsup` so the generated template exists when
// tsup type-checks the wrapper.

import * as esbuild from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { BASE_TEMPLATE } from "./baseTemplate.js";

const SRC_DIR = dirname(fileURLToPath(import.meta.url));
const GEN_DIR = join(SRC_DIR, "gen");
const APP_ENTRY = join(SRC_DIR, "app", "main.tsx");
const STYLES = join(SRC_DIR, "app", "styles.css");
const OUT_FILE = join(GEN_DIR, "template.ts");

// Tiny inline plugin that stubs Node-only built-ins reached only from
// dead branches in our transitive deps (e.g. `@bosonprotocol/metadata`'s
// `buildUuid` falls back to `require("crypto")` when `typeof window ===
// "undefined"` — that branch is unreachable in a browser bundle, but
// esbuild can't tree-shake it without help). The stub is a minimal
// no-op surface; if any of these modules is *actually* used at runtime
// in the browser the call will fail loudly, which is the behaviour we
// want — better than silently shipping broken code.
const NODE_BUILTIN_STUBS: Record<string, string> = {
  crypto: 'export default {}; export const randomUUID = () => "";',
};
const stubNodeBuiltinsPlugin: esbuild.Plugin = {
  name: "stub-node-builtins",
  setup(build) {
    const filter = new RegExp(`^(${Object.keys(NODE_BUILTIN_STUBS).join("|")})$`);
    build.onResolve({ filter }, (args) => ({ path: args.path, namespace: "node-stub" }));
    build.onLoad({ filter: /.*/, namespace: "node-stub" }, (args) => ({
      contents: NODE_BUILTIN_STUBS[args.path],
      loader: "js",
    }));
  },
};

async function buildAppBundle(): Promise<string> {
  const result = await esbuild.build({
    entryPoints: [APP_ENTRY],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: "es2020",
    minify: true,
    sourcemap: false,
    jsx: "automatic",
    jsxDev: false,
    loader: { ".css": "empty" },
    define: {
      "process.env.NODE_ENV": JSON.stringify("production"),
    },
    plugins: [stubNodeBuiltinsPlugin],
    logLevel: "warning",
  });
  if (result.outputFiles.length !== 1) {
    throw new Error(
      `x402-paywall/build: expected exactly 1 output file from esbuild, got ${result.outputFiles.length}`,
    );
  }
  return result.outputFiles[0].text;
}

async function readStyles(): Promise<string> {
  return readFile(STYLES, "utf8");
}

function splice(template: string, marker: string, content: string): string {
  const idx = template.indexOf(marker);
  if (idx === -1) {
    throw new Error(`x402-paywall/build: base template is missing marker ${marker}`);
  }
  return template.slice(0, idx) + content + template.slice(idx + marker.length);
}

async function main(): Promise<void> {
  const [appBundle, css] = await Promise.all([buildAppBundle(), readStyles()]);

  let html = BASE_TEMPLATE;
  html = splice(html, "<!--CSS-->", css);
  html = splice(html, "<!--JS-->", appBundle);

  await mkdir(GEN_DIR, { recursive: true });
  const file = `// Generated by \`src/build.ts\` — do not edit by hand.
// Re-run \`pnpm --filter @bosonprotocol/x402-paywall build:app\` after
// modifying anything under \`src/app/\`, \`src/baseTemplate.ts\`, or
// \`src/app/styles.css\`.

export const EVM_ESCROW_PAYWALL_TEMPLATE = ${JSON.stringify(html)};
`;
  await writeFile(OUT_FILE, file);

  const sizeKb = (Buffer.byteLength(html, "utf8") / 1024).toFixed(1);
  console.log(`x402-paywall/build: wrote ${OUT_FILE} (${sizeKb} KB)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
